In [4]:
import numpy as np  #alias

In [5]:
lst1 = [1,2,3]
arr1 = np.array(lst1)

In [6]:
type(lst1)

list

In [7]:
type(arr1)

numpy.ndarray

In [10]:
lst2 = [[1,2],[4,6],[7,8]]
np.array(lst2)

array([[1, 2],
       [4, 6],
       [7, 8]])

#### Built-in Methods to create Arrays

##### arange

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.arange(9,2)

array([], dtype=int64)

##### zeros and ones

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros((4,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### linspace 

returns evenly spaces numbers over a specified interval

In [21]:
np.linspace(0,12,4)

array([ 0.,  4.,  8., 12.])

In [22]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

##### eye

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### Random


Rand : array with random samples from a uniform distribution over [0,1)

In [35]:
np.random.rand(4)

array([0.32432616, 0.66485037, 0.06087214, 0.74432849])

In [38]:
np.random.rand(4,4)

array([[0.49931309, 0.90016938, 0.09212319, 0.8505192 ],
       [0.50377858, 0.46355338, 0.76498051, 0.29088173],
       [0.76977488, 0.2219465 , 0.75280926, 0.9355712 ],
       [0.59586694, 0.2761087 , 0.73776978, 0.50173049]])

In [39]:
#randn: return array with samples from a 'standard normal' distribution (sigma = 1)

In [41]:
np.random.randn(50)

array([-4.51053144e-02,  7.82729519e-01, -1.21190670e+00,  8.33440364e-01,
       -5.62960753e-01, -3.21301713e-01,  1.41298151e+00, -1.41429689e+00,
       -4.72338824e-01, -1.66992884e+00,  5.99872763e-01, -7.64885284e-01,
        3.77982751e-01, -9.31119107e-01, -1.74527208e+00, -4.22484692e-01,
       -1.56548002e+00,  8.03187794e-01, -6.83016494e-01, -1.03244344e+00,
        3.46644307e-01, -5.25196503e-01,  7.37666276e-01, -9.60953116e-01,
       -7.45227038e-01, -1.82845524e-01,  1.54996165e-02,  9.73849970e-04,
       -3.36660382e-02,  7.78621325e-01,  1.37161017e+00, -1.26111964e+00,
        1.71752371e+00, -3.31913079e-01, -5.53141367e-01, -8.74636072e-01,
       -1.44809843e+00,  6.30589766e-01,  1.58677564e+00,  1.34313871e+00,
        6.10639033e-01, -1.35391617e+00,  1.04304946e+00, -6.86039747e-01,
        6.43193177e-01, -8.39502701e-01,  1.95402765e+00,  9.06454717e-01,
        5.64245559e-01, -7.64447162e-02])

In [43]:
np.random.randn(3,4)

array([[ 0.62937466,  0.58484817, -0.03966379,  0.36454443],
       [ 0.56315414,  1.21879428, -0.64200892,  2.59161666],
       [-0.15985486,  1.42333622,  1.94054389, -3.65765747]])

##### randint

In [46]:
np.random.randint(1,100)

99

In [47]:
np.random.randint(1,100,13)

array([32,  6, 55, 74, 10, 43, 46, 27, 54, 36, 60, 86, 35])

In [53]:
np.random.randint(51,121,(4,5))

array([[110,  86, 113,  66,  64],
       [ 72, 108, 114,  59,  93],
       [110,  72,  97,  62, 109],
       [100,  62,  70,  67,  79]])

#### seed

set the random state, so that we generate same 'random' results over and over again

In [94]:
np.random.seed(11)
np.random.randint(1,100,11)

array([26, 64, 81, 92, 82, 56, 14, 77, 34, 72, 83])

#### Array Attributes and Methods

In [102]:
arr = np.arange(30)
ranarr = np.random.randint(0,50,10)

In [103]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [104]:
#reshape
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [105]:
arr.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [107]:
ranarr

array([ 6, 43,  0, 15, 32, 23, 27,  6, 25, 43])

In [106]:
ranarr.max()

43

In [108]:
ranarr.argmax()

1

In [109]:
ranarr.min()

0

In [110]:
ranarr.argmin()

2

#### Attributes

In [111]:
#shape
arr.shape

(30,)

In [117]:
len(arr)

30

In [113]:
arr.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [116]:
arr.reshape(30,1).shape

(30, 1)

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])