In [1]:
import numpy as np

In [8]:
arr = np.arange(10,21)

#### Bracket Indexing and Selection

In [9]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[-1]

20

In [11]:
arr[0:6]

array([10, 11, 12, 13, 14, 15])

#### Broadcasting

In [14]:
arr2 = np.array([1,2,3,4,5,6])

arr2

array([1, 2, 3, 4, 5, 6])

In [16]:
sliced_arr = arr2[0:3]

In [18]:
sliced_arr[:] = 99

In [19]:
sliced_arr

array([99, 99, 99])

In [20]:
arr2

array([99, 99, 99,  4,  5,  6])

#### data is not copied. sliced_arr is just a view of the original array. This is done to avoid memory problem

In [22]:
x = [1,2,3,4,5,6]
y = x[:2]

In [24]:
y[1] = 99

In [25]:
y

[1, 99]

In [26]:
x

[1, 2, 3, 4, 5, 6]

In [27]:
#to get a copy, do following
arr_copy = arr.copy()

In [29]:
sliced_arr = arr_copy[0:3]

In [30]:
sliced_arr[:] = 99

In [31]:
sliced_arr

array([99, 99, 99])

In [32]:
arr_copy

array([99, 99, 99, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### Indexing in 2-D Matrices

In [35]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d   #for rows, top to bottom and for columns, its left to right

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr_2d[1]

array([4, 5, 6])

In [38]:
arr_2d[1][-1]

6

In [39]:
arr_2d[1,-1]

6

In [48]:
arr_2d_prac = np.array(([61,22,39,109],[49,53,16,98],[17,89,79,43],[1,2,3,4]))

In [49]:
arr_2d_prac

array([[ 61,  22,  39, 109],
       [ 49,  53,  16,  98],
       [ 17,  89,  79,  43],
       [  1,   2,   3,   4]])

In [42]:
#61
arr_2d_prac[0,0]

61

In [43]:
arr_2d_prac[2,2]

79

In [44]:
arr_2d_prac[-1,-2]

79

In [45]:
arr_2d_prac[-1,2]

79

In [46]:
#slice
arr_2d_prac[1:,1:]

array([[53, 16, 98],
       [89, 79, 43]])

In [47]:
arr_2d_prac[-2:,-3:]

array([[53, 16, 98],
       [89, 79, 43]])

In [50]:
arr_2d_prac[0:2,2:]

array([[ 39, 109],
       [ 16,  98]])

### Conditional selection

In [51]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [53]:
bool_arr = arr>4 

In [54]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [61]:
arr[arr <= 4]

array([1, 2, 3, 4])

In [56]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])