In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Arithmetic

In [3]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr/arr

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_63579/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
1/arr

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_63579/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#### Universal Array Functions

In [9]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
#exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [12]:
np.log(arr)

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_63579/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
np.add(1.0, 4.0)

5.0

In [14]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.add(x1, x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [15]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [16]:
x2

array([0., 1., 2.])

#### Summary Statistics

In [18]:
arr.sum()

45

In [19]:
arr.mean()

4.5

In [20]:
arr.max()

9

#### Axis Logic

matrices : axis 0 --> rows, axis 1 --> columns

In [24]:
arr_2d = np.arange(100,132,2).reshape(4,4)
arr_2d

array([[100, 102, 104, 106],
       [108, 110, 112, 114],
       [116, 118, 120, 122],
       [124, 126, 128, 130]])

In [25]:
arr_2d.sum()

1840

In [26]:
arr_2d.sum(axis=0)

array([448, 456, 464, 472])

In [27]:
arr_2d.sum(axis=1)

array([412, 444, 476, 508])

In [28]:
arr_2d.max(axis=1)

array([106, 114, 122, 130])